### ISSUE TITLE
Windbg exit from spawn_debugger()

### ISSUE THREAD

**Issue by FrancescoLucarini** [masthoon/pwintools#11]
Wanted to ask if there is a way that windbg reamain opened from spawn_debugger or if there are other functions that help with debugging,.
Thanks in advance

**Comment by masthoon** [comment]
The Process.\_\_del\_\_ method will kill all the processes spawned. 

If your Python script doesn't exit (e.g. placing ``input('Press enter to exit')`` at the end of your script), the debugger process should stay alive.
