### ISSUE TITLE
use pywin32?

### ISSUE THREAD

**Issue by gogo2464** [masthoon/pwintools#13]
https://github.com/mhammond/pywin32 seem more mature than pythonForWindows. In my humble opinion we could use it.

Fell free to give your opinion.

**Comment by masthoon** [comment]
Personally, I don't like the C/C++ part of ``pywin32`` (binary release + compiler required to build). 
This project was also a good use case for playing around with [PythonForWindows](https://github.com/hakril/PythonForWindows), so I don't intend to change it.

Feel free to open your fork of pwintools.

**Comment by gogo2464** [comment]
If there is no need to use pywin32 I will not add it.

Do not worry, I actively contribute to this issue instead: https://github.com/masthoon/pwintools/issues/4  :)
