### ISSUE TITLE
Python 2&3: PythonForWindows won't install automatically failing pwintools installation

### ISSUE THREAD

**Issue by TAbdiukov** [masthoon/pwintools#2]
Python 2&3: PythonForWindows won't install automatically

If I do,
```
pip install pwintools
```
or
```
cd pwintools
pip install .
```
The installation will fail because Pip will fail to find a PythonForWindows  package (not only of v0.4, but any)

However, if I download the repo off Github (whether `master` or `dev`. Dev supports Py3), and then manually install it, and then install pwintools, having removed PythonForWindows lines from setup.py, the installation and, most importantly, usage of pwintools gets set up correctly

I wonder if anyone else experiences the same issue

**Comment by masthoon** [comment]
Oh thanks for the report, I will take a look tomorrow.
PythonForWindows python 3 support is still in development, I will wait for next release to update the dependency but I can make this repo python 3 compatible in the meantime.

**Comment by masthoon** [comment]
It should work now if you have git.exe in your PATH.
Leaving this issue open until python 3 is supported.

**Comment by masthoon** [comment]
Actually we should open a new issue. Closing this one :)
@TAbdiukov let me know if the setup.py change works for you.
