### ISSUE TITLE
write in the readme and in the doc that you need to download windbg

### ISSUE THREAD

**Issue by gogo2464** [masthoon/pwintools#8]
To use the spawn_debugger() function we need to have wingdb installed in 'C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\windbg.exe' this is not mentionned nowhere.

I also suggest to check in the code and notify the user if this is not installed.

**Comment by gogo2464** [comment]
EDIT: actually I will directly write the doc in pwntools. In upstream.

**Comment by masthoon** [comment]
You can change the debugger path manually yes, it's not documented I agree.
