### ISSUE TITLE
remove xrange

### ISSUE THREAD

**Issue by gogo2464** [masthoon/pwintools#9]
This commit https://github.com/masthoon/pwintools/commit/5dada369e002134db257ab4278575f913bf8b2ea has some good features like remove string not set with bytes.

Sadly it also decrase the python3 style.

xrange is a python2 stuff and should be removed. I want to avoid that developper in the future spend hours to understand how xrange works to finally realize this is a python2 stuff.

I have already removed it in an old commit but somebody has put it back. So instead of remove it again and start a war I decided to open an issue to discuss and debate on what is the best between range and xrange.

**Comment by masthoon** [comment]
Ok, completed in commit e62634e99bf33d6745d8c642d3c7f028699c1958

**Comment by gogo2464** [comment]
In my humble opinion this is same. I think this should be completely removed.

**Comment by masthoon** [comment]
I will not drop Python 2 support, range in Python 2 may trigger OverflowError on large ranges thus xrange is necessary.
